# KB stack
version: '3.2'
volumes:
  db:
  kbvol:
services:
  killbill:
    image: killbill/killbill:0.22.26
    ports:
      - "8080:8080"
      - "8000:8000"
      - "12345:12345"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_SERVER_TEST_MODE=false
    networks:
      - killbill
    volumes:
      - type: bind
        source: /home/kb022
        target: /tmp
      - type: volume
        source: kbvol
        target: /var/lib/killbill
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: any
  kaui:
    image: killbill/kaui:latest
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
      - KAUI_KILLBILL_API_KEY=bob
      - KAUI_KILLBILL_API_SECRET=lazar
    networks:
      - killbill
    depends_on:
      - db
      - killbill
    deploy:
      restart_policy:
        condition: any 
  db:
    image: killbill/mariadb:0.22
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
    networks:
      - killbill
    deploy:
      restart_policy:
        condition: any
  safProxy:
    image: sachgits/safproxy:0.2
    ports:
      - "3000:3000"
    depends_on:
      - killbill
    networks:
      - killbill
    deploy:
      restart_policy:
        condition: any
networks:
  killbill:
    driver: bridge
